import { build } from "esbuild";

await build({
  entryPoints: [new URL("./vendor-entry.mjs", import.meta.url).pathname],
  outfile: new URL("../client/generated/vendor.js", import.meta.url).pathname,
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "es2020",
  minify: true,
  legalComments: "eof",
  banner: { js: "// Generated by scripts/build-vendor.mjs. Do not edit." },
});
console.log("vendor.js built");
